spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/ticketing
    username: ticket
    password: ticketpwd
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://127.0.0.1:5434/ticketing
    user: ticket
    password: ticketpwd
  sql:
    init:
      mode: never
  main:
    banner-mode: off
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER:}
    password: ${MAILTRAP_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

app:
  stripe:
    secret: sk_test_xxx
    webhook-secret: whsec_xxx  
  notification:
    reminderHours: 24
  jwt:
    accessSecret: change_me_access_secret
    refreshSecret: change_me_refresh_secret
    accessTtlMinutes: 15
    refreshTtlDays: 14