spring:
  datasource:
    url: jdbc:postgresql://db:5432/ticketing
    username: ticket
    password: ticketpwd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

server:
  port: 8080
